### ISSUE TITLE
array types in type checking

### ISSUE THREAD

**Issue by dio4ev** [W4RH4WK/UIBK-703602-Compiler-Construction#2]
I think currently. something like that is accepted:

`
int i = 8;
int a [4];
i = a;
`

**Comment by W4RH4WK** [comment]
This shouldn't be accepted, the type of a variable should also take into acount whether it's an array or scalar. Maybe even the size of the array as we only support 1D, statically sized arrays.

In your example, while `i` is of type `int`, `a` is of type `int[4]`. Assigning an `int[4]` to an `int` should yield an error by the type-checker.
